baseurl = "http://bepsays.com/"
title = "bepsays.com"
languageCode = "no-nn"
MetaDataFormat = "yaml"
NewContentEditor = "gedit"
PygmentsStyle = "trac"
CanonifyUrls = "true"
PluralizeListTitles = "false"
PygmentsCodeFences = "true"
PaginatePath = "side"
EnableEmoji = true
Paginate = 11
DefaultContentLanguage = "nn"
DefaultContentLanguageInSubdir = true

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[params]
    description = "bepsays.com sine tankar om dette og hint."

[permalinks]
  post = "/:year/:month/:day/:slug/"
  english = "/:year/:month/:day/:slug/"

[Taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[Languages]
[Languages.nn]
weight = 1
title = "Bepsays på norsk"

[Languages.en]
weight = 2
title = "Bepsays in English"
[Languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true

