baseurl = "http://bepsays.com/"
title = "bepsays.com"
languageCode = "no-nn"
metaDataFormat = "yaml"
newContentEditor = "gedit"
pygmentsStyle = "trac"
canonifyUrls = "true"
pluralizeListTitles = "false"
pygmentsCodeFences = "true"
paginatePath = "side"
enableEmoji = true
paginate = 11
defaultContentLanguage = "nn"
defaultContentLanguageInSubdir = false
sectionPagesMenu = "sect"

disqusShortname = "bepsays"

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[permalinks]
  pol = "/:year/:month/:day/:slug/"
  fun = "/:year/:month/:day/:slug/"
  art = "/:year/:month/:day/:slug/"
  tec = "/:year/:month/:day/:slug/"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params]
description = "bepsays.com. Om dette og hint."

[languages]
[languages.nn]
languageName = "Nynorsk"
weight = 1
title = "Bepsays på norsk"

[languages.en]
languageName = "English"
weight = 2
title = "Bepsays in English"
paginatePath = "page"
description = "bepsays.com. Abut this and that."
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true

