baseurl = "http://bepsays.com/"
title = "bepsays.com"
languageCode = "no-nn"

PygmentsStyle = "bw"

[markdown]
    angledQuotes = true

[params]
    description = "bepsays.com sine tankar om dette og hint."

[permalinks]
  post = "/:year/:month/:day/:slug/"
  english = "/:year/:month/:day/:slug/"

[Taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"


