baseurl = "http://bepsays.com/"
title = "bepsays.com"
languageCode = "no-nn"
MetaDataFormat = "yaml"
NewContentEditor = "gedit"
PygmentsStyle = "trac"
CanonifyUrls = "true"
PluralizeListTitles = "false"
PygmentsCodeFences = "true"
PaginatePath = "side"
Paginate = 11
[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[params]
    description = "bepsays.com sine tankar om dette og hint."

[permalinks]
  post = "/:year/:month/:day/:slug/"
  english = "/:year/:month/:day/:slug/"

[Taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"


